name: commupro1
description: A new Flutter project.



publish_to: "none"




version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"




dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  cached_network_image: ^3.2.0
  jiffy: ^5.0.0
  faker: ^2.0.0
  iconsax: ^0.0.8
  ionicons: ^0.2.1
  rive: ^0.9.1
  flutter_svg: ^1.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  kf_drawer: ^1.2.1

  table_calendar: ^3.0.3






  flutter_lints: ^2.0.0





flutter:



  uses-material-design: true


  assets:
    - assets/Backgrounds/
    - assets/icons/
    - assets/avatars/
    - assets/RiveAssets/













  fonts:
    - family: Intel
      fonts:
        - asset: assets/Fonts/Inter-Regular.ttf
        - asset: assets/Fonts/Inter-SemiBold.ttf
          weight: 600
    - family: Poppins
      fonts:
        - asset: assets/Fonts/Poppins-Bold.ttf
          weight: 700



